word_pairs = [

    ("Forest", "Jungle"),
    ("Ocean", "Sea"),
    ("Teacher", "Professor"),
    ("Laptop", "Computer"),
    ("Bread", "Cake"),
    ("Coffee", "Tea"),
    ("Pizza", "Burger"),
    ("Football", "Basketball"),
    ("Tiger", "Lion"),
    ("Phone", "Tablet"),

    ("River", "Lake"),
    ("Mountain", "Hill"),
    ("Desert", "Beach"),
    ("Train", "Metro"),
    ("Bus", "Taxi"),
    ("Pen", "Pencil"),
    ("Notebook", "Diary"),
    ("Bottle", "Glass"),
    ("Chair", "Sofa"),
    ("Table", "Desk"),

    ("Doctor", "Nurse"),
    ("Police", "Soldier"),
    ("Pilot", "Driver"),
    ("Chef", "Cook"),
    ("Singer", "Dancer"),
    ("Actor", "Comedian"),
    ("Artist", "Painter"),
    ("King", "Queen"),
    ("Prince", "Knight"),
    ("Robot", "Android"),

    ("Apple", "Orange"),
    ("Banana", "Mango"),
    ("Grapes", "Berry"),
    ("Potato", "Tomato"),
    ("Onion", "Garlic"),
    ("Rice", "Pasta"),
    ("Burger", "Sandwich"),
    ("Chocolate", "Candy"),
    ("Juice", "Milkshake"),
    ("Ice Cream", "Frozen Yogurt"),

    ("Dog", "Wolf"),
    ("Cat", "Leopard"),
    ("Horse", "Donkey"),
    ("Cow", "Buffalo"),
    ("Goat", "Sheep"),
    ("Monkey", "Chimpanzee"),
    ("Snake", "Lizard"),
    ("Shark", "Whale"),
    ("Eagle", "Falcon"),
    ("Duck", "Goose"),

    ("School", "College"),
    ("Library", "Bookstore"),
    ("Temple", "Church"),
    ("Hospital", "Clinic"),
    ("Airport", "Station"),
    ("Hotel", "Resort"),
    ("Market", "Mall"),
    ("Gym", "Stadium"),
    ("Cinema", "Theater"),
    ("Park", "Garden"),

    ("Sun", "Moon"),
    ("Star", "Planet"),
    ("Rain", "Storm"),
    ("Snow", "Ice"),
    ("Fire", "Smoke"),
    ("Wind", "Breeze"),
    ("Cloud", "Fog"),
    ("Thunder", "Lightning"),
    ("Volcano", "Mountain"),
    ("Earthquake", "Tsunami"),

    ("Car", "Jeep"),
    ("Bike", "Scooter"),
    ("Truck", "Trailer"),
    ("Ship", "Boat"),
    ("Helicopter", "Airplane"),
    ("Rocket", "Satellite"),
    ("Submarine", "Yacht"),
    ("Engine", "Motor"),
    ("Battery", "Charger"),
    ("Camera", "Drone"),

    ("WhatsApp", "Telegram"),
    ("Instagram", "Snapchat"),
    ("YouTube", "Netflix"),
    ("Google", "Yahoo"),
    ("Amazon", "Flipkart"),
    ("Spotify", "Apple Music"),
    ("Facebook", "Twitter"),
    ("Chrome", "Safari"),
    ("Windows", "Linux"),
    ("Android", "iPhone"),

    ("Cricket", "Baseball"),
    ("Tennis", "Badminton"),
    ("Hockey", "Rugby"),
    ("Chess", "Checkers"),
    ("Swimming", "Diving"),
    ("Boxing", "Wrestling"),
    ("Karate", "Judo"),
    ("Cycling", "Skating"),
    ("Running", "Jogging"),
    ("Yoga", "Meditation"),

    ("Gold", "Silver"),
    ("Diamond", "Ruby"),
    ("Clock", "Watch"),
    ("Mirror", "Window"),
    ("Candle", "Lamp"),
    ("Key", "Lock"),
    ("Bag", "Suitcase"),
    ("Wallet", "Purse"),
    ("Ring", "Bracelet"),
    ("Shoes", "Slippers"),

    ("Batman", "Superman"),
    ("Iron Man", "Captain America"),
    ("Thor", "Loki"),
    ("Harry Potter", "Hermione"),
    ("Naruto", "Sasuke"),
    ("Pikachu", "Raichu"),
    ("Tom", "Jerry"),
    ("Mickey", "Donald"),
    ("Shrek", "Fiona"),
    ("Mario", "Luigi"),
]